#!/usr/bin/env bash
#
# Repo lint: static checks over this repo's own scripts and data files.
#
#   .github/scripts/lint.sh                      run every check
#   .github/scripts/lint.sh --require-shellcheck fail (instead of skipping) if
#                                                the shellcheck binary is absent
#   .github/scripts/lint.sh --require-append-only fail (instead of skipping) if
#                                                the append-only evidence check
#                                                cannot resolve its base ref
#
# Zero dependencies beyond python3 and (optionally) shellcheck, matching the
# harness's stdlib-only rule -- there is no venv and no package manifest to
# install. Run by `npm run lint` and by the `lint` job in
# .github/workflows/ci.yml, so local and CI results are identical.
#
# Ported from `2AMLogic/gf180-bandgap`'s .github/scripts/lint.sh (via
# `2AMLogic/gf180-gate-driver`, the more recent port) per this repo's
# harness-bootstrap issue (#8). The DUT-freshness step the source port
# carries is present here too (step 4), against this repo's one generated
# DUT: layout/gds/cml_driver_core.spice -> layout/sim/cml_driver_core_dut.spice
# (issue #34).
#
# Scope: files this repo owns. The vendored `.loom/` and `.claude/` trees and
# the `loom.sh` wrapper are installed and regenerated by external tooling
# (Loom / Repo Skills) -- linting them would gate this repo's PRs on upstream
# code it does not maintain.
#
# Portable to the bash 3.2 that ships with macOS (no mapfile/readarray).
#
# Exit codes: 0 pass, 1 a check failed.

set -uo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "${REPO_ROOT}" || exit 1

REQUIRE_SHELLCHECK=0
EVIDENCE_ARGS=()
for arg in "$@"; do
  case "${arg}" in
    --require-shellcheck) REQUIRE_SHELLCHECK=1 ;;
    --require-append-only) EVIDENCE_ARGS+=(--require-append-only) ;;
    -h|--help) sed -n '2,24p' "${BASH_SOURCE[0]}"; exit 0 ;;
    *) echo "unknown option: ${arg}" >&2; exit 1 ;;
  esac
done

status=0

# Tracked, repo-owned files matching one glob, collected into the `files`
# array. Tracked-only, so generated/ignored artefacts are never linted; the
# vendored .loom/ and .claude/ trees are excluded (see the header).
collect() {
  files=()
  while IFS= read -r -d '' path; do
    files+=("${path}")
  done < <(git ls-files -z -- "$1" ':!:.loom/**' ':!:.claude/**' ':!:loom.sh')
}

echo "== 1/7 shellcheck (shell scripts) =="
collect '*.sh'
if [ "${#files[@]}" -eq 0 ]; then
  echo "no shell scripts tracked"
elif command -v shellcheck >/dev/null 2>&1; then
  printf '%s\n' "${files[@]}"
  if ! shellcheck "${files[@]}"; then
    echo "FAIL: shellcheck"
    status=1
  fi
elif [ "${REQUIRE_SHELLCHECK}" -eq 1 ]; then
  echo "FAIL: shellcheck is not installed (--require-shellcheck)"
  status=1
else
  echo "SKIP: shellcheck is not installed (brew install shellcheck / apt-get install shellcheck)"
fi

echo
echo "== 2/7 python syntax =="
collect '*.py'
if [ "${#files[@]}" -eq 0 ]; then
  echo "no python files tracked"
else
  printf '%s\n' "${files[@]}"
  # A syntax error anywhere in the harness fails here instead of halfway
  # through a simulation run.
  if ! python3 -m compileall -q "${files[@]}"; then
    echo "FAIL: python syntax"
    status=1
  fi
fi

echo
echo "== 3/7 json well-formedness =="
collect '*.json'
if [ "${#files[@]}" -eq 0 ]; then
  echo "no json files tracked"
else
  printf '%s\n' "${files[@]}"
  # Testbench manifests (sim/<slug>/testbench/tb.json), sim/pdk.json and
  # package.json are all hand-edited; a stray comma should not reach a
  # simulation run.
  if ! python3 -c '
import json
import sys

bad = 0
for path in sys.argv[1:]:
    try:
        with open(path, encoding="utf-8") as handle:
            json.load(handle)
    except (OSError, ValueError) as exc:
        print(f"{path}: {exc}")
        bad += 1
sys.exit(1 if bad else 0)
' "${files[@]}"; then
    echo "FAIL: malformed json"
    status=1
  fi
fi

echo
echo "== 4/7 generated DUT freshness (layout/sim) =="
# layout/sim/cml_driver_core_dut.spice is mechanically derived from the
# LVS-signed-off extracted netlist layout/gds/cml_driver_core.spice (model
# binding, vsubs->VSS body tie, wrapper pin order) and is committed so an
# evidence record can cite a stable sha256. A hand-edit of either file, or a
# re-extraction of the layout not followed by a regeneration, would silently
# make every post-layout record cite a netlist that is not the one under
# layout/. --check re-derives it and diffs; it changes nothing on disk.
if ! python3 layout/scripts/gen_cml_driver_core_dut.py --check; then
  echo "FAIL: layout/sim/cml_driver_core_dut.spice is stale"
  echo "  regenerate with: python3 layout/scripts/gen_cml_driver_core_dut.py"
  status=1
fi

echo
echo "== 5/7 evidence records (sim/*/records) =="
# The schema in sim/README.md -- required fields (including the
# conditionally-required Operating point / Transient settings pair for a
# rate-bearing record), <record-id> naming, the corner-id grammar (including
# the bit-rate axis), and the append-only rule -- enforced instead of merely
# documented. Tracked files only, same as collect() above; the append-only
# half diffs against the merge base with origin/main and SKIPs (unless
# --require-append-only) where that ref does not resolve.
if ! python3 sim/check_records.py ${EVIDENCE_ARGS[@]+"${EVIDENCE_ARGS[@]}"}; then
  echo "FAIL: evidence records"
  status=1
fi

echo
echo "== 6/7 LVS signoff verdicts (layout/lvs_reports) =="
# Every drawn cell is signed off with a pair of `klt lvs` runs: the intact
# cell (must `match`) and its deliberately-shorted twin (must `mismatch`).
# The second is the negative control -- the only evidence the first one's
# `match` means anything. Issue #129: a drift in the installed klt's
# extraction deck (klayout-tools#1196) silently flipped one `_shorted`
# control to `match`, and nothing noticed, because a committed report saying
# `match` looks like good news. Enforced here instead of merely documented:
# a negative control that stops failing fails the build. No PDK, no klt, no
# klayout -- reads the committed reports only.
if ! python3 layout/scripts/check_lvs_signoff.py; then
  echo "FAIL: LVS signoff verdicts"
  echo "  inspect with: python3 layout/scripts/check_lvs_signoff.py --list"
  status=1
fi

echo
echo "== 7/7 characterization-report coverage (measurements) =="
# measurements/characterization.md calls itself "the single aggregated,
# current summary ... citing every evidence record". That completeness claim
# is the whole value of the artifact: a spec row absent from it is supposed
# to mean no evidence exists, not that nobody updated the rollup. Issue #142:
# the Monte Carlo mismatch record (#23, landed 2026-08-15) was never added,
# and the report's own coverage section went on asserting no such record
# existed for ten days and five subsequent revisions. Enforced here instead of
# documented: a tracked evidence record the rollup does not cite fails the
# build. No PDK, no ngspice -- reads committed files only.
if ! python3 sim/check_record_citations.py; then
  echo "FAIL: characterization-report coverage"
  echo "  inspect with: python3 sim/check_record_citations.py --list"
  status=1
fi

echo
if [ "${status}" -eq 0 ]; then
  echo "PASS: lint clean."
else
  echo "FAIL: lint found problems."
fi
exit "${status}"
