#!/usr/bin/env bash
#
# Repo lint: static checks over this repo's own scripts and data files.
#
#   .github/scripts/lint.sh                      run every check
#   .github/scripts/lint.sh --require-shellcheck fail (instead of skipping) if
#                                                the shellcheck binary is absent
#   .github/scripts/lint.sh --require-append-only fail (instead of skipping) if
#                                                the append-only evidence check
#                                                cannot resolve its base ref
#
# Zero dependencies beyond python3 and (optionally) shellcheck, matching the
# harness's stdlib-only rule -- there is no venv and no package manifest to
# install. Run by `npm run lint` and by the `lint` job in
# .github/workflows/ci.yml, so local and CI results are identical.
#
# Ported from `2AMLogic/gf180-bandgap`'s .github/scripts/lint.sh (via
# `2AMLogic/gf180-gate-driver`, the more recent port) per this repo's
# harness-bootstrap issue (#8), trimmed to this repo's current scope: no
# DUT-freshness step (no design/netlist -> sim/dut generation exists yet
# here).
#
# Scope: files this repo owns. The vendored `.loom/` and `.claude/` trees and
# the `loom.sh` wrapper are installed and regenerated by external tooling
# (Loom / Repo Skills) -- linting them would gate this repo's PRs on upstream
# code it does not maintain.
#
# Portable to the bash 3.2 that ships with macOS (no mapfile/readarray).
#
# Exit codes: 0 pass, 1 a check failed.

set -uo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "${REPO_ROOT}" || exit 1

REQUIRE_SHELLCHECK=0
EVIDENCE_ARGS=()
for arg in "$@"; do
  case "${arg}" in
    --require-shellcheck) REQUIRE_SHELLCHECK=1 ;;
    --require-append-only) EVIDENCE_ARGS+=(--require-append-only) ;;
    -h|--help) sed -n '2,24p' "${BASH_SOURCE[0]}"; exit 0 ;;
    *) echo "unknown option: ${arg}" >&2; exit 1 ;;
  esac
done

status=0

# Tracked, repo-owned files matching one glob, collected into the `files`
# array. Tracked-only, so generated/ignored artefacts are never linted; the
# vendored .loom/ and .claude/ trees are excluded (see the header).
collect() {
  files=()
  while IFS= read -r -d '' path; do
    files+=("${path}")
  done < <(git ls-files -z -- "$1" ':!:.loom/**' ':!:.claude/**' ':!:loom.sh')
}

echo "== 1/4 shellcheck (shell scripts) =="
collect '*.sh'
if [ "${#files[@]}" -eq 0 ]; then
  echo "no shell scripts tracked"
elif command -v shellcheck >/dev/null 2>&1; then
  printf '%s\n' "${files[@]}"
  if ! shellcheck "${files[@]}"; then
    echo "FAIL: shellcheck"
    status=1
  fi
elif [ "${REQUIRE_SHELLCHECK}" -eq 1 ]; then
  echo "FAIL: shellcheck is not installed (--require-shellcheck)"
  status=1
else
  echo "SKIP: shellcheck is not installed (brew install shellcheck / apt-get install shellcheck)"
fi

echo
echo "== 2/4 python syntax =="
collect '*.py'
if [ "${#files[@]}" -eq 0 ]; then
  echo "no python files tracked"
else
  printf '%s\n' "${files[@]}"
  # A syntax error anywhere in the harness fails here instead of halfway
  # through a simulation run.
  if ! python3 -m compileall -q "${files[@]}"; then
    echo "FAIL: python syntax"
    status=1
  fi
fi

echo
echo "== 3/4 json well-formedness =="
collect '*.json'
if [ "${#files[@]}" -eq 0 ]; then
  echo "no json files tracked"
else
  printf '%s\n' "${files[@]}"
  # Testbench manifests (sim/<slug>/testbench/tb.json), sim/pdk.json and
  # package.json are all hand-edited; a stray comma should not reach a
  # simulation run.
  if ! python3 -c '
import json
import sys

bad = 0
for path in sys.argv[1:]:
    try:
        with open(path, encoding="utf-8") as handle:
            json.load(handle)
    except (OSError, ValueError) as exc:
        print(f"{path}: {exc}")
        bad += 1
sys.exit(1 if bad else 0)
' "${files[@]}"; then
    echo "FAIL: malformed json"
    status=1
  fi
fi

echo
echo "== 4/4 evidence records (sim/*/records) =="
# The schema in sim/README.md -- required fields (including the
# conditionally-required Operating point / Transient settings pair for a
# rate-bearing record), <record-id> naming, the corner-id grammar (including
# the bit-rate axis), and the append-only rule -- enforced instead of merely
# documented. Tracked files only, same as collect() above; the append-only
# half diffs against the merge base with origin/main and SKIPs (unless
# --require-append-only) where that ref does not resolve.
if ! python3 sim/check_records.py ${EVIDENCE_ARGS[@]+"${EVIDENCE_ARGS[@]}"}; then
  echo "FAIL: evidence records"
  status=1
fi

echo
if [ "${status}" -eq 0 ]; then
  echo "PASS: lint clean."
else
  echo "FAIL: lint found problems."
fi
exit "${status}"
