#!/usr/bin/env python3
"""Item 8's generic evidence envelope -- generated, never hand-edited.

`klt signoff`'s generic-evidence path (klayout-tools#1152) is the only
ingestion route for T1 item 8, the one checklist item with no `klt` verb:
the block writes a small `kind: "generic"` JSON wrapper asserting the
characterization report's own verdict. The contract
(klayout-tools `docs/cli/signoff.md` -> "Generic evidence") makes the
envelope's `provenance` optional and its field names the author's choice,
and -- because of exactly that -- `klt signoff` never re-hashes a generic
citation's input (`input_verified` is `null` for every generic envelope, by
design). The freshness chain for item 8 therefore has a link only this
repo can enforce:

    characterization.md -> envelope.provenance.input.content_hash
    envelope hash        -> manifest evidence["8"].content_hash   (klt grades this)
    manifest             -> signoff/signoff.json                  (CI byte-compares)

This script owns the first link. Run bare, it regenerates
`signoff/characterization-envelope.json` deterministically from the
committed report (same convention as layout/scripts/gen_*.py -- the record
is generated or it is nothing). Run with `--check`, it re-derives the
envelope and diffs it against the committed one without writing, so CI fails
when `measurements/characterization.md` changed without the envelope
(regenerate both, then the manifest pin, then the record -- see
signoff/README.md "Regenerating the record").

The same "term" as the DUT-freshness checks in .github/scripts/lint.sh
step 4: a mechanically derived file committed so a citation can name a
stable sha256, --check so a stale copy fails the build instead of rotting.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
REPORT = REPO_ROOT / "measurements" / "characterization.md"
ENVELOPE = Path(__file__).resolve().parent / "characterization-envelope.json"

SUMMARY = (
    "Block-level characterization report: one aggregated, current artifact "
    "citing a committed evidence record behind every per-spec-row verdict "
    "(analog DR rows, digital synthesis/P&R/LVS/SDF re-sim/STA rows incl. "
    "per-corner Fmax), with gaps named explicitly rather than omitted; its "
    "record-coverage is machine-checked by sim/check_record_citations.py in "
    "the lint CI job. Scope, not silently inflated: a digital-partition power "
    "rollup across the corner set is not yet part of this report (named in "
    "the report's own not-yet-covered section)."
)

STATUS = "pass"


def sha256_file(path: Path) -> str:
    return "sha256:" + hashlib.sha256(path.read_bytes()).hexdigest()


def build_envelope() -> dict:
    if not REPORT.is_file():
        print(f"missing input: {REPORT}", file=sys.stderr)
        raise SystemExit(1)
    return {
        "schema_version": 1,
        "kind": "generic",
        "status": STATUS,
        "summary": SUMMARY,
        "source": "measurements/characterization.md",
        "provenance": {
            "tool": (
                "gf180-tmds-tx generic wrapper, generated by "
                "signoff/gen_characterization_envelope.py (klt signoff "
                "docs/cli/signoff.md 'Generic evidence', klayout-tools#1152)"
            ),
            "input": {
                "file": "measurements/characterization.md",
                "content_hash": sha256_file(REPORT),
            },
        },
    }


def render(envelope: dict) -> str:
    return json.dumps(envelope, indent=2, ensure_ascii=False) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="compare the committed envelope against a fresh derivation; "
        "write nothing, exit 1 on drift (the CI mode)",
    )
    parser.add_argument(
        "-o",
        "--output",
        default=str(ENVELOPE),
        help=f"envelope path to write (default: {ENVELOPE})",
    )
    args = parser.parse_args()

    fresh = render(build_envelope())
    if args.check:
        if not ENVELOPE.is_file():
            print(f"missing envelope: {ENVELOPE}", file=sys.stderr)
            return 1
        committed = ENVELOPE.read_text(encoding="utf-8")
        if committed == fresh:
            print("characterization envelope fresh: matches the committed report.")
            return 0
        print(
            f"FAIL: {ENVELOPE} is stale against {REPORT} (or hand-edited).",
            file=sys.stderr,
        )
        print(
            "Regenerate it, the manifest's item-8 content_hash pin, and the "
            "signoff record together -- see signoff/README.md.",
            file=sys.stderr,
        )
        return 1

    out = Path(args.output)
    out.write_text(fresh, encoding="utf-8")
    print(f"wrote {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
