"""Deck composition and ngspice execution for one PVT point.

Ported from `2AMLogic/gf180-bandgap` (sim/harness/runner.py). ``compose_deck``
gains two adaptations for this repo's transient/rate-axis claims (see
``sim/harness/corners.py`` and ``sim/harness/testbench.py``'s module
docstrings): it emits a ``rate_val``/``rate_nom`` parameter pair when the
point carries a bit rate, and it emits ``.options reltol=/abstol=/vntol=``
from the testbench's declared ``transient`` settings so those tolerances
actually take effect in the deck rather than being decorative metadata. The
measurement regex is also widened to accept ngspice's ``meas`` command
output (``m_trise  = 1.23e-09 targ=... trig=...``), not just the harness's
own ``let``/``print`` output (``m_vout = 1.23e-09``) -- a transient testbench
uses ``meas`` for threshold-crossing measurements (rise/fall time) that a
plain vector expression cannot express.

A ``tb.measure`` manifest entry whose value starts with ``TRIG `` (see
``_is_raw_meas_expr``) is rendered as a raw ``meas tran m_<name> <value>``
control-block command instead of a ``let m_<name> = <value>`` vector
expression -- e.g. ``"trise_10_90": "TRIG v(vdiff) VAL=-0.4 RISE=1 TARG
v(vdiff) VAL=0.4 RISE=1"``. Every other ``tb.measure`` entry (the
gf180-bandgap convention) is unaffected.
"""

from __future__ import annotations

import re
import shutil
import subprocess
import time
from concurrent.futures import ThreadPoolExecutor
from dataclasses import dataclass, field
from pathlib import Path

from .corners import PvtPoint
from .pdk import Pdk
from .testbench import Testbench

NGSPICE = "ngspice"
DEFAULT_TIMEOUT_S = 300

# Matches both this harness's own `let`/`print` output for a length-1 vector
# ("m_vout = 6.9043645202e-01", anchored to end of line) and ngspice's
# `meas` command output ("m_trise  = 8.00000e-10 targ=... trig=...",
# trailing text after the number) -- the leading `^\s*m_` anchor plus the
# unanchored tail is what lets one regex parse both without also matching
# `meas`'s own `targ=`/`trig=` sub-fields (neither starts with `m_`).
_MEAS_RE = re.compile(r"^\s*m_(\w+)\s*=\s*([-+]?[0-9.]+(?:[eE][-+]?[0-9]+)?)")
_ERROR_RE = re.compile(r"^\s*(?:Error|ERROR|Fatal|fatal error|doAnalyses:)", re.MULTILINE)


class NgspiceMissing(RuntimeError):
    pass


def ngspice_version() -> str:
    exe = shutil.which(NGSPICE)
    if not exe:
        raise NgspiceMissing(
            "ngspice not found on PATH.\n"
            "  macOS:  brew install ngspice\n"
            "  Debian: apt-get install ngspice"
        )
    out = subprocess.run(
        [exe, "--version"], capture_output=True, text=True, check=False
    ).stdout
    for line in out.splitlines():
        if "ngspice-" in line:
            return line.strip().lstrip("* ").strip()
    return out.strip().splitlines()[0] if out.strip() else "unknown"


def compose_deck(tb: Testbench, pdk: Pdk, point: PvtPoint) -> str:
    """Build the complete, self-contained ngspice deck for one PVT point."""
    rate_note = "n/a" if point.rate_mbps is None else f"{point.rate_mbps:g} Mbps/lane"
    lines: list[str] = [
        f"* {tb.name} @ {point.corner_id} -- GENERATED by sim/harness, do not edit",
        f"* corner={point.corner.name} ({point.corner.description})",
        f"* temp={point.temp_c} C  vdd={point.vdd} V  rate={rate_note}  pdk={pdk.variant}@{pdk.version}",
        "",
        "* ---- PVT parameters -------------------------------------------------",
        f".param vdd_nom={tb.nominal_supply_v!r}",
        f".param vdd_val={point.vdd!r}",
        f".param temp_c={point.temp_c!r}",
    ]
    if point.rate_mbps is not None:
        # rate_nom is the nearest of the testbench's declared rates_mbps to
        # this point's own rate -- for the un-adapted single-rate case
        # (rates_mbps has one entry) it is simply that entry; a testbench
        # sweeping both spec rows (as sim/smoke-cml-pair does) gets a
        # ratio-style reference matching whichever row this point belongs to.
        lines.append(f".param rate_val={point.rate_mbps!r}")
    for key, value in tb.params.items():
        lines.append(f".param {key}={value}")

    lines += [
        "",
        "* ---- gf180mcu models ------------------------------------------------",
        f'.include "{pdk.design_include}"',
    ]
    for section in point.corner.sections:
        lines.append(f'.lib "{pdk.model_lib}" {section}')

    lines += [
        "",
        f".temp {point.temp_c!r}",
    ]
    for option in tb.options:
        lines.append(f".options {option}")
    for key in ("reltol", "abstol", "vntol"):
        if key in tb.transient:
            lines.append(f".options {key}={tb.transient[key]!r}")

    if tb.dut is not None:
        lines += [
            "",
            "* ---- device under test ----------------------------------------------",
            f"* provenance: {tb.dut_provenance_class}  sha256 {tb.dut_sha256}",
            f'.include "{tb.dut}"',
        ]

    lines += [
        "",
        "* ---- testbench ------------------------------------------------------",
        f'.include "{tb.netlist}"',
        "",
        "* ---- measurement ----------------------------------------------------",
        ".control",
        "set numdgt=10",
        "set noaskquit",
    ]
    lines += [f"  {analysis}" for analysis in tb.analyses]
    for name, expr in tb.measure.items():
        if _is_raw_meas_expr(expr):
            # A raw ngspice `meas` fragment (threshold-crossing measurements
            # -- rise/fall time -- that a `let` vector expression cannot
            # express). `meas` prints "m_<name> = <value> ..." itself, so no
            # separate `print` line is emitted for it below.
            lines.append(f"  meas tran m_{name} {expr}")
        else:
            lines.append(f"  let m_{name} = {expr}")
    for name, expr in tb.measure.items():
        if not _is_raw_meas_expr(expr):
            lines.append(f"  print m_{name}")
    lines += [".endc", ".end", ""]
    return "\n".join(lines)


def _is_raw_meas_expr(expr: str) -> bool:
    """Is this ``measure`` manifest entry a raw ``meas`` fragment (starts
    with ``TRIG``, case-insensitive) rather than a ``let`` vector expression?

    See ``sim/harness/testbench.py``'s module docstring and
    ``sim/README.md``'s measurement-convention section.
    """
    return expr.strip().upper().startswith("TRIG ")


@dataclass
class PointResult:
    point: PvtPoint
    status: str                                   # "ok" | "failed" | "error"
    measurements: dict[str, float] = field(default_factory=dict)
    missing: list[str] = field(default_factory=list)
    seconds: float = 0.0
    deck: str = ""
    log: str = ""
    message: str = ""

    def as_dict(self) -> dict:
        record = self.point.as_dict()
        record.update(
            {
                "status": self.status,
                "measurements": self.measurements,
                "seconds": round(self.seconds, 3),
                "deck": self.deck,
                "log": self.log,
            }
        )
        if self.missing:
            record["missing_measurements"] = self.missing
        if self.message:
            record["message"] = self.message
        return record


def parse_measurements(text: str) -> dict[str, float]:
    found: dict[str, float] = {}
    for line in text.splitlines():
        match = _MEAS_RE.match(line)
        if match:
            try:
                found[match.group(1)] = float(match.group(2))
            except ValueError:  # pragma: no cover - regex already constrains this
                continue
    return found


def run_point(
    tb: Testbench,
    pdk: Pdk,
    point: PvtPoint,
    workdir: Path,
    timeout_s: int = DEFAULT_TIMEOUT_S,
    log_dir: Path | None = None,
) -> PointResult:
    """Simulate one PVT point. Never raises for simulation failure.

    ``workdir`` holds the generated deck (scratch, disposable). ``log_dir``
    -- when given -- is where the raw ngspice output lands as
    ``<corner-id>.log``; that is the ``sim/<slug>/corners/<record-id>/``
    directory from ``sim/README.md``. It defaults to ``workdir`` so a
    throwaway run does not touch the evidence tree.
    """
    workdir.mkdir(parents=True, exist_ok=True)
    log_dir = workdir if log_dir is None else log_dir
    log_dir.mkdir(parents=True, exist_ok=True)
    deck_path = workdir / f"{point.corner_id}.spice"
    log_path = log_dir / f"{point.corner_id}.log"
    deck_path.write_text(compose_deck(tb, pdk, point))

    started = time.monotonic()
    try:
        proc = subprocess.run(
            [NGSPICE, "-b", str(deck_path)],
            capture_output=True,
            text=True,
            timeout=timeout_s,
            cwd=workdir,
            check=False,
        )
        output = proc.stdout + "\n" + proc.stderr
        returncode = proc.returncode
    except FileNotFoundError as exc:
        raise NgspiceMissing(str(exc)) from exc
    except subprocess.TimeoutExpired:
        elapsed = time.monotonic() - started
        log_path.write_text(f"TIMEOUT after {timeout_s}s\n")
        return PointResult(
            point=point,
            status="error",
            seconds=elapsed,
            deck=deck_path.name,
            log=log_path.name,
            message=f"ngspice timed out after {timeout_s}s",
        )
    elapsed = time.monotonic() - started
    log_path.write_text(output)

    measurements = parse_measurements(output)
    missing = [name for name in tb.measure if name not in measurements]

    if missing:
        errors = "; ".join(_ERROR_RE.findall(output)[:3])
        first_error = next(
            (line.strip() for line in output.splitlines() if _ERROR_RE.match(line)), ""
        )
        return PointResult(
            point=point,
            status="failed",
            measurements=measurements,
            missing=missing,
            seconds=elapsed,
            deck=deck_path.name,
            log=log_path.name,
            message=first_error or errors or f"ngspice exit {returncode}, no measurements parsed",
        )

    return PointResult(
        point=point,
        status="ok",
        measurements=measurements,
        seconds=elapsed,
        deck=deck_path.name,
        log=log_path.name,
    )


def run_grid(
    tb: Testbench,
    pdk: Pdk,
    points: list[PvtPoint],
    workdir: Path,
    jobs: int = 1,
    timeout_s: int = DEFAULT_TIMEOUT_S,
    on_result=None,
    log_dir: Path | None = None,
) -> list[PointResult]:
    """Run every PVT point; results come back in grid order regardless of jobs."""
    results: list[PointResult | None] = [None] * len(points)

    def _one(index_point):
        index, point = index_point
        result = run_point(tb, pdk, point, workdir, timeout_s=timeout_s, log_dir=log_dir)
        results[index] = result
        if on_result is not None:
            on_result(result)
        return result

    if jobs <= 1:
        for item in enumerate(points):
            _one(item)
    else:
        with ThreadPoolExecutor(max_workers=jobs) as pool:
            list(pool.map(_one, enumerate(points)))

    return [r for r in results if r is not None]
