# Timing constraints for tmds_encoder -- GENERATED by flow/sta_tmds_encoder.py
# (issue #83). Regenerated in place on every run; edit that driver, not this
# file. See the driver's docstring for why each assumption below is what it
# is -- every one of them is disclosed in the evidence record too.

# 720p60 pixel clock, 74.25 MHz (spec/tmds-tx.md §2). The encoder is a
# pixel-domain block: one 10-bit TMDS character per pixel clock.
create_clock -name clk -period 13.4680 [get_ports clk]

# #84 ran no clock-tree synthesis, so the clock net is an ordinary routed
# net. Propagate its real (unbalanced) delay rather than idealizing it, and
# add no uncertainty margin -- there is no CTS-derived skew budget to derive
# one from. The hold verdict this produces is therefore a PRE-CTS hold
# verdict.
set_propagated_clock [all_clocks]
set_clock_uncertainty 0.0000 [get_clocks clk]

# No block-boundary timing budget has been ratified for this block, so none
# is assumed: the whole period is available to the I/O paths. This is the
# most optimistic legal choice -- real surrounding logic can only make these
# slacks worse -- so a violation reported under it is a real violation.
set non_clk_inputs [get_ports {data[*] ctrl[*] de rst}]
set_input_delay 0.0000 -clock clk $non_clk_inputs
set_output_delay 0.0000 -clock clk [all_outputs]

# Stated design assumptions, not measurements: drive every primary input
# with the library's smallest inverter, and load every output with 4x that
# inverter's own input capacitance (0.006813 pF).
set_driving_cell -lib_cell gf180mcu_fd_sc_mcu9t5v0__inv_1 -pin ZN $non_clk_inputs
set_load 0.027252 [all_outputs]
